var lang = {
	en: {
		'g_logo':'WMID.com.ua Bot extension for marriage agency zolushka, dream, svadba, jump4love',
		'g_help':'Help',
		'g_bayact':'Buy activation',
		'g_balcklist':'Blacklist',
		'g_pisallist':'Writers',
		'g_infotags':'Variables:',
		'g_tagname':'name',
		'g_taglogin':'login',
		'g_tagage':'age',
		'g_taggrowth':'growth',
		'g_tagmass':'weight',
		'g_tagcountry':'country',
		'g_tagwork':'work',
		'g_tagcity':'city',
		'g_pay_to':'Paid for:',
		'g_tema':'Subject',
		'g_add':'Add',
		'g_edit':'Edit',
		'g_delete':'Delete',
		'g_notema':'-No Subject-',
		'g_temas':'-subjects-',
		'g_sendfor':'Send for',
		'g_for_online':'For online',
		'g_for_writers':'For writers',
		'g_for_matches':'For matches',
		'g_for_admirers':'For admirers',
		'g_for_favorites':'For favorites',
		'g_for_advanced':'For offline',
		'g_for_online_infinitely':'For online (infinitely)',
		'g_for_noanswered':'For not responded',
		'g_for_activedialog':'For active dialogue',
		'g_for_contactlist':'For contact list',
		'g_photos':'Photos',
		'g_nophoto':'-without photo-',
		'g_upload_delete':'Upload / delete',
		'g_upload':'-Upload-',
		'g_age_from':'Age from',
		'g_start_send':'Start',
		'g_stop_send':'Stop',
		'g_to':'to',
		'g_addidman':'Enter ID (can be somewhat, separated by commas)',
		'g_editwrite':'Edit the entry:',
		'g_addtema':'Enter subject',
		'g_addnewtema':'Enter new subject',
		'g_realydelletter':'Are you sure you want to delete the letter?',
		'g_selecttemaletter':'Select subject for letter',
		'g_limitleterisfail':'The posting is reached limit  today. Come back tomorrow.',
		'g_addtextletter':'Enter the text of the letter!',
		'g_addpisalman':'Add writers',
		'g_sending':'Posting',
		'g_alreadydend':'Send',
		'g_waitsend':'wait',
		'g_unknown':'unknown',
		'g_quotaextended':'Local storage is full',
		'g_sendingstoped':'Posting stopped',
		'g_sendinggo':'Posting',
		'g_sendingfinished':'Posting finished',
		'g_gettest':'Get 2 days FREE',
		'g_notactivation':'You have not days for activation',
		
		'g_for_favorites':'Favorites',
		'g_for_platil':'Paying men',
		'g_tocountries':'Country',
		'g_wait':'Wait ...',
		'g_error_link':'You want to send the link! It is forbidden!',
		'g_error_email':'You want to send Email! It is forbidden!',
		'g_addtextmessage':'Add message!',
		'g_pusto':'- Empty -',
		'g_all':'All',
		'g_nolistman':'No men for posting',
		'g_clearhistory':'Clean history',
		'g_clean_contact':'Clean contacts',
		'g_cleancookie':'Clean cookies',
		
		's_actualonline':'Actual Online',
		's_platilmanonline':'Paying men',
		's_back':'<- Back',
		's_delselectmoreman':'* before removal, select one or more of the men on the list',
		's_for_interest':'Interested',
		's_speed':'Speed',
		's_slow':'Slow',
		's_normal':'Normal',
		's_fast':'Fast',
		's_stop_send':'Stop',
		's_pause_send':'Pause',
		's_report_send':'Report',
		's_activechats':'Active chats',
		's_errorminmaxage':'Minimum age may not exceed the maximum',
		},
	ru: {
		'g_logo':'WMID.com.ua Bot программы для брачных агенств для золушки, дрима, свадьбы, джампа',
		'g_help':'Справка',
		'g_bayact':'Продлить активацию',
		'g_balcklist':'Черный список',
		'g_pisallist':'Список писателей',
		'g_infotags':'Переменные:',
		'g_tagname':'имя',
		'g_taglogin':'логин',
		'g_tagage':'возраст',
		'g_tagheight':'рост',
		'g_tagmass':'вес',
		'g_tagcountry':'страна',
		'g_tagwork':'работа',
		'g_tagcity':'город',
		'g_pay_to':'Оплачено до:',
		'g_tema':'Тема',
		'g_add':'Добавить',
		'g_edit':'Править',
		'g_delete':'Удалить',
		'g_notema':'-нет тем-',
		'g_temas':'-темы-',
		'g_tsel':'Цель',
		'g_for_online':'По списку онлайн',
		'g_for_writers':'По писателям',
		'g_for_matches':'По парам',
		'g_for_admirers':'По поклонникам',
		'g_for_favorites':'По фаворитам',
		'g_for_advanced':'По списку офлайн',
		'g_for_online_infinitely':'По списку онлайн (бесконечно)',
		'g_for_noanswered':'По не ответившим',
		'g_for_activedialog':'По активным диалогам',
		'g_for_contactlist':'По контакт-листу',
		'g_photos':'Фотки',
		'g_nophoto':'-без фотографии-',
		'g_upload_delete':'Загрузить / удалить',
		'g_upload':'-Загрузить-',
		'g_age_from':'Взраст от',
		'g_start_send':'Начать рассылку',
		'g_stop_send':'Остановить рассылку',
		'g_to':'до',
		'g_addidman':'Введите ID (можно несколько, через запятую)',
		'g_editwrite':'Отредактируйте запись:',
		'g_addtema':'Введите тему письма',
		'g_addnewtema':'Введите новую тему письма',
		'g_realydelletter':'Вы действительно хотите удалить письмо',
		'g_selecttemaletter':'Выберите тему для рассылки',
		'g_limitleterisfail':'На сегодня лимит рассылки исчерпан. Приходите завтра.',
		'g_addtextletter':'Введите текст письма!',
		'g_addpisalman':'Заполните писателей',
		'g_sending':'Рассылка',
		'g_alreadydend':'Отправлено',
		'g_waitsend':'ожидает',
		'g_unknown':'неизвестно',
		'g_quotaextended':'Локальное хранилище переполнено',
		'g_sendingstoped':'Рассылка остановлена',
		'g_sendinggo':'Идет рассылка',
		'g_sendingfinished':'Рассылка завершена',
		'g_gettest':'Получить 2 дня бесплатно',
		'g_notactivation':'У Вас закончились дни активации',
		
		'g_for_favorites':'Фаворитам',
		'g_for_platil':'Платящим',
		'g_tocountries':'По странам',
		'g_wait':'Подождите...',
		'g_error_link':'Вы хотите рассылать ссылку! Это запрещено!',
		'g_error_email':'Вы хотите рассылать Email! Это запрещено!',
		'g_addtextmessage':'Напишите сообщение!',
		'g_pusto':'- Пусто -',
		'g_all':'Все',
		'g_for_search':'Поиск',
		'g_nolistman':'Нечего рассылать',
		'g_clearhistory':'Очистить историю расслок',
		'g_clean_contact':'Очистить контакт-лист',
		'g_cleancookie':'Очистить куки',
		
		's_actualonline':'Актуальный Online',
		's_platilmanonline':'Платящих мужчин',
		's_back':"<- Назад",
		's_delselectmoreman':'* перед удалением выберите одного или несколько мужчин в списке',
		's_for_interest':'Интересующиеся',
		's_speed':'Скорость',
		's_slow':'Медленно',
		's_normal':'Нормально',
		's_fast':'Быстро',
		's_stop_send':'Стоп',
		's_pause_send':'Пауза',
		's_report_send':'Отчет приглашений',
		's_activechats':'Активные чаты',
		's_errorminmaxage':'Минимальный возраст не может превышать максимальный',
		's_':'',
		}
};
var navl = navigator.languages[0].substring(0,2);
	navl = (navl!='ru'&&navl!='en'?'en':navl);
lang = lang[navl];